### ISSUE TITLE
Question: Commercial friendly license

### ISSUE THREAD

**Issue by mjukel** [kevoree-modeling/mwDB#17]
This is a very interesting project. Do you consider switching to a commercial-friendly license to broaden its versatility ?

**Comment by dukeboard** [comment]
Hi, 
Interesting remarks, this is a very discussed topic in the dev team.
We are preparing a new licence schema with commercial options.
Details are not fixed yet, but we will allow commercial exploitation maybe with double licences, or by splitting the core and some plugins. This will be solve in the next coming month at latest. Best regards

**Comment by agarciadom** [comment]
I am also interested in this. Our open source Hawk tool (https://github.com/mondo-project/mondo-hawk) is EPL-licensed, and the GPLv3 license would prevent us from integrating mwDB at the moment.

**Comment by dukeboard** [comment]
Hi, 
We just discussed this internally and here is the flavour of what we can change shortly (i.e. next week). We plan to switch the licence of the following modules to Apache Licence 2: Core / LevelDB / WS / MinimalMachineLearning. For all these modules we will open to external contribution. For other advances plugins, we will certainly go for a double licence model (GPLv3 / commercial). Therefore MWG will be business friendly and easy to integrate in European and  academic projects. Only advanced storage and machine learning will remain protected.

**Comment by agarciadom** [comment]
That sounds reasonable to me :-).

**Comment by mjukel** [comment]
A (little late) happy new year for everybody !
The license change as outlined by @dukeboard  would be very good news. I would be grateful if you could give me a date for that, because I need to decide wether I can use mwDB for a project starting soon.
It could very well be that in the future this project will need advanced mwDB plugins also, and commercial licensing for that would not be a problem. However, I can only use it if the core uses a commercial friendly license.

**Comment by gnain** [comment]
Hi,
I confirm that we are currently in the process to change the licence to an Apache 2.0.
This process is going along with the creation of a spin-off company, and the negotiations with our University takes more time than expected. The licence change is planned to occur in January, but we cannot be more precise at the time.
We'll let you know as soon as the change is effective.

By the way, could you give us a bit more details on your profile and application domain for our records ?
You can send this feedback by email directly if you do not want to publicly disclose these information.

**Comment by agarciadom** [comment]
I do not mind disclosing it publicly. Hawk is an indexer that monitors models and mirrors them incrementally into graph databases for fast querying. Hawk can use Neo4j or OrientDB as backends right now - Neo4j is complicated due to its GPL license and OrientDB doesn't quite have the performance we'd like. If mwDB were released under the Apache 2.0 license, we'd look into integrating it as a backend and comparing its performance and capabilities against the OrientDB one.

**Comment by gnain** [comment]
@bluezio Thanks for the feedback :-) We are working on the Apache 2.0 release, but face some IP complications ! We should get a GO in January.
Wishing you all a nice day.

**Comment by dukeboard** [comment]
Hopefully the next release will be under AL2 licence :-)

**Comment by dukeboard** [comment]
Hi, we have a great news we finally got the ok for AL2.0 licence :-).
Now MWG is release since version 11 in business friendly AL2.0 licence.

For various reasons, the project has been renamed GreyCat.
In addition GreyCat will be supported by developer from the Datathings startup.
This change of course nothing for the licence and the code base (except package rename).
We will be happy to meet you again on the following repository:
https://github.com/datathings/greycat

The documentation, logo and press release will be done soon. 
We hope this new organisation will help to make GreyCat a nice documented and stable product.

See you there. Regards. François

**Comment by mjukel** [comment]
This is great news, thank you very much. I'm looking forward to use "GreyCat" and I'm curious about what else Datathings will have to offer.
